apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: java-redis-client
  name: java-redis-client
spec:
  containers:
  - env:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
    - name: REDIS_HOST
      value: redis-10698.c256.us-east-1-2.ec2.cloud.redislabs.com
    - name: REDIS_PORT
      value: "10698"
    - name: REDIS_PASSWORD
      value: gc8fMWDVhTk6hKY7aWHZsSq4ELht5Kst
    image: nectiadocker2000/test-redis-client:v1
    name: java-redis-client
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
