apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-redis-client
  name: java-redis-client
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8083
  selector:
    app: java-redis-client
  type: NodePort
